import type { ContactSubmission, Client, Deal } from "@/lib/types/crm";

// Mock Contact Submissions
export const mockSubmissions: ContactSubmission[] = [
    {
        id: "sub_001",
        fullName: "Budi Santoso",
        email: "budi.santoso@tokopedia.com",
        phone: "+62 812-3456-7890",
        company: "Tokopedia",
        projectType: "Mobile App Development",
        estimatedTimeline: "3-6 months",
        budgetRange: "IDR 500-750 Million",
        description: "We need a comprehensive e-commerce mobile application with advanced features including AR product preview and AI-powered recommendations.",
        status: "NEW",
        submittedAt: new Date("2025-12-15T10:30:00").toISOString(),
        isSpam: false,
        notes: null,
    },
    {
        id: "sub_002",
        fullName: "Siti Nurhaliza",
        email: "siti@bukalapak.com",
        phone: "+62 813-9876-5432",
        company: "Bukalapak",
        projectType: "Web Application",
        estimatedTimeline: "2-4 months",
        budgetRange: "IDR 300-500 Million",
        description: "Redesign our merchant dashboard with modern UI/UX and real-time analytics capabilities.",
        status: "REVIEWED",
        submittedAt: new Date("2025-12-14T14:20:00").toISOString(),
        isSpam: false,
        notes: "Interested in React + Next.js stack",
    },
    {
        id: "sub_003",
        fullName: "Ahmad Hidayat",
        email: "ahmad@gojek.co.id",
        phone: "+62 821-5555-1234",
        company: "Gojek",
        projectType: "Enterprise Software",
        estimatedTimeline: "6-12 months",
        budgetRange: "IDR 1-2 Billion",
        description: "Internal fleet management system with GPS tracking, driver performance analytics, and automated dispatch.",
        status: "CONTACTED",
        submittedAt: new Date("2025-12-10T09:15:00").toISOString(),
        isSpam: false,
        notes: "Had initial call, very interested",
    },
    {
        id: "sub_004",
        fullName: "Rina Wijaya",
        email: "rina.wijaya@traveloka.com",
        phone: "+62 811-2222-3333",
        company: "Traveloka",
        projectType: "API Development",
        estimatedTimeline: "1-2 months",
        budgetRange: "IDR 150-250 Million",
        description: "Build RESTful API for hotel booking integration with third-party systems.",
        status: "CLOSED",
        submittedAt: new Date("2025-12-08T16:45:00").toISOString(),
        isSpam: false,
        notes: "Converted to client",
    },
    {
        id: "sub_005",
        fullName: "John Scammer",
        email: "freemoney@spam.xyz",
        phone: "+1 999-999-9999",
        company: null,
        projectType: "Website",
        estimatedTimeline: null,
        budgetRange: "IDR 10-20 Million",
        description: "I need website very cheap!!! Best price guaranteed!!!",
        status: "NEW",
        submittedAt: new Date("2025-12-17T23:55:00").toISOString(),
        isSpam: true,
        notes: "Marked as spam",
    },
    {
        id: "sub_006",
        fullName: "Dewi Lestari",
        email: "dewi@shopee.co.id",
        phone: "+62 815-7777-8888",
        company: "Shopee Indonesia",
        projectType: "Mobile App Development",
        estimatedTimeline: "4-6 months",
        budgetRange: "IDR 600-900 Million",
        description: "Seller mobile app with inventory management, order processing, and analytics dashboard.",
        status: "NEW",
        submittedAt: new Date("2025-12-16T11:00:00").toISOString(),
        isSpam: false,
        notes: null,
    },
    {
        id: "sub_007",
        fullName: "Rudi Hartono",
        email: "rudi@blibli.com",
        phone: "+62 816-4444-5555",
        company: "Blibli",
        projectType: "Web Application",
        estimatedTimeline: "3-5 months",
        budgetRange: "IDR 400-600 Million",
        description: "Customer loyalty program platform with gamification features and reward management.",
        status: "REVIEWED",
        submittedAt: new Date("2025-12-13T13:30:00").toISOString(),
        isSpam: false,
        notes: "Reviewing proposal",
    },
    {
        id: "sub_008",
        fullName: "Maya Putri",
        email: "maya@tiket.com",
        phone: "+62 817-6666-7777",
        company: "Tiket.com",
        projectType: "Mobile App Development",
        estimatedTimeline: "2-3 months",
        budgetRange: "IDR 250-400 Million",
        description: "Flight booking mobile app with price comparison and seat selection features.",
        status: "NEW",
        submittedAt: new Date("2025-12-17T08:20:00").toISOString(),
        isSpam: false,
        notes: null,
    },
];

// Mock Clients with nested Contacts and Deals
export const mockClients: Client[] = [
    {
        id: "client_001",
        name: "Traveloka",
        contacts: [
            {
                id: "contact_001",
                clientId: "client_001",
                name: "Rina Wijaya",
                email: "rina.wijaya@traveloka.com",
                phone: "+62 811-2222-3333",
                position: "Head of Engineering",
            },
            {
                id: "contact_002",
                clientId: "client_001",
                name: "Andi Kusuma",
                email: "andi.kusuma@traveloka.com",
                phone: "+62 812-3333-4444",
                position: "Product Manager",
            },
        ],
        deals: [
            {
                id: "deal_001",
                clientId: "client_001",
                title: "API Development for Hotel Integration",
                description: "Build RESTful API for hotel booking integration with third-party systems",
                value: 200000000,
                stage: "NEGOTIATION",
                createdAt: new Date("2025-12-09T10:00:00").toISOString(),
            },
            {
                id: "deal_002",
                clientId: "client_001",
                title: "Mobile App Maintenance",
                description: "Ongoing maintenance and bug fixes for iOS and Android apps",
                value: 50000000,
                stage: "WON",
                createdAt: new Date("2025-11-15T14:00:00").toISOString(),
            },
        ],
    },
    {
        id: "client_002",
        name: "Gojek",
        contacts: [
            {
                id: "contact_003",
                clientId: "client_002",
                name: "Ahmad Hidayat",
                email: "ahmad@gojek.co.id",
                phone: "+62 821-5555-1234",
                position: "VP of Technology",
            },
        ],
        deals: [
            {
                id: "deal_003",
                clientId: "client_002",
                title: "Fleet Management System",
                description: "Internal system with GPS tracking and driver analytics",
                value: 1500000000,
                stage: "NEW",
                createdAt: new Date("2025-12-11T09:30:00").toISOString(),
            },
        ],
    },
    {
        id: "client_003",
        name: "Bukalapak",
        contacts: [
            {
                id: "contact_004",
                clientId: "client_003",
                name: "Siti Nurhaliza",
                email: "siti@bukalapak.com",
                phone: "+62 813-9876-5432",
                position: "Senior Developer",
            },
            {
                id: "contact_005",
                clientId: "client_003",
                name: "Benny Susanto",
                email: "benny@bukalapak.com",
                phone: "+62 814-8888-7777",
                position: "CTO",
            },
        ],
        deals: [
            {
                id: "deal_004",
                clientId: "client_003",
                title: "Merchant Dashboard Redesign",
                description: "Modern UI/UX with real-time analytics",
                value: 400000000,
                stage: "NEW",
                createdAt: new Date("2025-12-14T15:00:00").toISOString(),
            },
            {
                id: "deal_005",
                clientId: "client_003",
                title: "Payment Gateway Integration",
                description: "Failed project - scope too large",
                value: 300000000,
                stage: "LOST",
                createdAt: new Date("2025-10-20T10:00:00").toISOString(),
            },
        ],
    },
    {
        id: "client_004",
        name: "Tokopedia",
        contacts: [
            {
                id: "contact_006",
                clientId: "client_004",
                name: "Budi Santoso",
                email: "budi.santoso@tokopedia.com",
                phone: "+62 812-3456-7890",
                position: "Director of Product",
            },
        ],
        deals: [
            {
                id: "deal_006",
                clientId: "client_004",
                title: "E-commerce Mobile App",
                description: "Comprehensive mobile app with AR and AI features",
                value: 625000000,
                stage: "NEGOTIATION",
                createdAt: new Date("2025-12-15T11:00:00").toISOString(),
            },
        ],
    },
    {
        id: "client_005",
        name: "Blibli",
        contacts: [
            {
                id: "contact_007",
                clientId: "client_005",
                name: "Rudi Hartono",
                email: "rudi@blibli.com",
                phone: "+62 816-4444-5555",
                position: "Head of Digital",
            },
        ],
        deals: [
            {
                id: "deal_007",
                clientId: "client_005",
                title: "Loyalty Program Platform",
                description: "Gamification and reward management system",
                value: 500000000,
                stage: "WON",
                createdAt: new Date("2025-11-25T13:00:00").toISOString(),
            },
        ],
    },
];

// Flat deals array for Kanban board
export const mockDeals: Deal[] = mockClients.flatMap((client) => client.deals);
